encode:
  sudo:
    use: true

git:
  # the local git folder path where most of the repositories will be cloned into
  path: /home/git-repo
  user:
    name: "Your Name"
    email: "email@softvision.ro"
  clone:
    mango:
      origin:   git@github.com:svnvcristea/Mango.git
      upstream: git@github.com:ps-dev-lapp/Mango.git
  GitHub:
    keys: "mango sugarBash SugarCRMCodeSniffer stacks stackDeployer nusim"
    mango: git@github.com:svnvcristea/Mango.git
    sugarBash: git@github.com:svnvcristea/sugarBash.git
    SugarCRMCodeSniffer: git@github.com:svnvcristea/SugarCRMCodeSniffer.git
    stacks: git@github.com:sugarcrm/stacks.git
    stackDeployer: git@github.com:svnvcristea/stack-deployer.git
    nusim: git@github.com:sugarcrm-ps/nusim.git
    nomad: git@github.com:sugarcrm/nomad.git
    refinery: git@github.com:sugarcrm/refinery.git
    translations: git@github.com:sugarcrm/translations.git

vpn:
  conf: /etc/vpnc/sugarvpn.conf

mount:
  fstab:
    SugarEPS:
      0: "192.168.56.101:/srv/www/htdocs"
      1: "192.168.56.101:/etc/apache2/vhosts.d"
    php54:
      0: "192.168.56.15:/var/www/html"
    php55_oracle12c:
      0: "192.168.56.14:/var/www/html"

backup:
  serverip: 192.168.99.10
  mountpoint: "/mnt/BackupSynk"
  path: "$PATH:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  command:
    mount: mount.cifs
    umount: umount
    rsync: grsync
    domain: DOMAIN1
    username: user.name

db:
  mysql:
    type: mysql
    port: 13306
    connect:
      host: localhost
      user: root
      pass: sugarcrm
    setRoot:
      host: %
      user: root
      pass: pspass
  oracle:
    type: oci8
    port: 1521
    connect:
      host: localhost
      user: system
      pass: manager
    setRoot:
      host: 0.0.0.0
      user: system
      pass: manager

nusim:
  tmppath: /tmp/nusim
  sugar:
    mango: /home/vagrant/git-repo/Mango
    name: Turbinado
    version: 7.7.0.0
    flavor: ult
    admin:
      user: admin
      pass: asdf
    db:
      key: oracle
    license: replace-me!
  build:
    number: cs00
    upgrade:
      number: csr2246
      to: csr0001
    with:
      nomad: true
    branch:
      nomad: v3_0
      translations: 7_7
      refinery: master
    checkout:
      nomad: 882c5667800d6d5f90c081abca3ea863dead0cb0
      translations: 94eebf2483e97662fb04a79c88c97b9f9bc7833b
      refinery: f23ddc7ebf4ad2b9ab786209761e3ac648fe725b

stacksON:
  repo: git@github.com:sugarcrm/stacks.git
  path: ~/git-repo/stacks/vagrant-on
  stack: oracle12c

day:
  on:
    0: "son up"
    1: skype
    2: hipchat4
    3: thunderbird
    4: firefox
    5: /usr/bin/google-chrome-stable
  off:
    0: "son halt"
    1: "bash $0 1"
