option:
  0:
    name: Quit
    func: "exit 1"
  1:
    name: Backup
    func: backup
  2:
    name: Mount
    func: "menu option_2_opt"
    opt:
      0:
        name: Main menu
        func: menu option
      1:
        name: SugarEPS
        func: mountFstab SugarEPS
      2:
        name: Stack php54
        func: mountFstab php54
      3:
        name: Stack oracle12c
        func: mountFstab oracle12c
  3:
    name: VPN
    func: "menu option_3_opt"
    opt:
      0:
        name: Main menu
        func: menu option
      1:
        name: VPN Connect
        func: "vpn connectSugar"
      2:
        name: VPN Kill
        func: "vpn kill"
      3:
        name: VPN status
        func: "vpn status"

  4:
    name: Git
    func: "menu option_4_opt"
    opt:
      0:
        name: Main Menu
        func: menu option
      1:
        name: Config Global
        func: "gitConfig global"
      2:
        name: Clone Github
        func: "gitConfig clone"
      3:
        name: Init SugarCRM Build
        func: "gitConfig initSugarBuild"
      4:
        name: Mango
        func: "menu option_4_opt_4_opt"
        opt:
          0:
            name: Main Menu
            func: menu option
          1:
            name: clone
            func: "gitMango clone"
          2:
            name: post checkout
            func: "gitMango postCheckout"
          3:
            name: patch
            func: "gitMango patch"
  5:
    name: xbuild
    func: "xbuild"
  6:
    name: "nusim"
    func: "menu option_6_opt"
    opt:
      0:
        name: Main Menu
        func: menu option
      1:
        name: Check
        func: "newsim check"
      2:
        name: Install
        func: "newsim install"
      3:
        name: Use
        func: "menu option_6_opt_3_opt"
        opt:
          0:
            name: Nusim Menu
            func: menu option_6_opt
          1:
            name: install Turbinado instance
            func: "newsim installInstance"
          2:
            name: create install pack
            func: "newsim createInstallPack"
  7:
    name: "DB"
    func: "menu option_7_opt"
    opt:
      0:
        name: Main Menu
        func: menu option
      1:
        name: MySQL
        func: "menu option_7_opt_1_opt"
        opt:
          0:
            name: Main Menu
            func: menu option_7_opt
          1:
            name: show users
            func: dbMySQL showUsers
          2:
            name: user privileges
            func: dbMySQL showUserPrivileges
          3:
            name: set root
            func: dbMySQL setRoot
          4:
            name: DB size
            func: dbMySQL dbSize
          5:
            name: import dump
            func: importSQLDump
      2:
        name: ORACLE
        func: "menu option_7_opt_2_opt"
        opt:
          0:
            name: Main Menu
            func: menu option
          1:
            name: showUsers
            func: dbOracle showUsers
          2:
            name: changePass
            func: dbOracle changePass
  8:
    name: Sugar DevEnv
    func: "menu option_8_opt"
    opt:
      0:
        name: Main Menu
        func: menu option
      1:
        name: PHPUnit
        func: "menu option_8_opt_1_opt"
        opt:
          0:
            name: Back menu
            func: menu option_8_opt
          1:
            name: install
            func: PHPUnit install
          2:
            name: PHPUnit Sugar Customization Test Suite
            func: PHPUnit runCustomizationTestSuite
  9:
    name: System Info
    func: "menu option_9_opt"
    opt:
      0:
        name: Main Menu
        func: menu option
      1:
        name: Full info
        func: sysInfo
      2:
        name: OS
        func: sysInfo OS
      3:
        name: disk
        func: sysInfo disk
      4:
        name: Actual folder size
        func: sysInfo foldersSize
      5:
        name: Actual folder write benchmark
        func: sysInfo writeTest
      6:
        name: Top 10 sub-folders size
        func: sysInfo top10folders
      7:
        name: Virtual Box info
        func: sysInfo vbox
  10:
    name: CI Simulator
    func: "menu option_10_opt"
    opt:
      0:
        name: Main Menu
        func: menu option
      1:
        name: Create Build
        func: ci createInstallPack
  11:
    name: "Shortcut - gitMango patch"
    func: "gitMango patch $2"
